# 右/左轮电机使能（bit0-bit1 / bit3-bit4）：0不修改 1使能 2失能
uint8 right_wheel_enable_cmd
uint8 left_wheel_enable_cmd

# 右/左轮电机复位（bit2 / bit5）：0不修改 1复位
uint8 right_wheel_reset_cmd
uint8 left_wheel_reset_cmd

# 充电（bit14）：0不修改 1打开 2关闭
uint8 charging_on_cmd
---
# Response
bool success