/**:
  ros__parameters:
    # Voxel Filter
    rough_leaf_size:  0.6
    refine_leaf_size: 0.1

    # TF Frames
    map_frame_id:  "map"
    odom_frame_id: "odom"
    laser_frame_id: "front_laser_link"
    base_frame_id:  "base_footprint"

    # Topics
    pointcloud_topic: "/livox/lidar"
    rviz_initial_pose_topic: "/initialpose"
    pose_topic: "/icp_pose"

    # ICP Search Parameters
    thresh:          1.0
    xy_offset:       0.5
    yaw_offset:      30.0
    yaw_resolution:  10.0

    # Initial Guess [x, y, z, roll, pitch, yaw]
    initial_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # Output Options
    publish_pose: true
    publish_tf:   true